apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-byqg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-byqg@sha256:77ae5be9973592f48a60c5ed9e774a5d1503b9cfbe482f46245a0f73c6abb527
        name: my-nodejs
        resources: {}
status: {}
